module Const
  PREFECTURES = {
    hokkaido: "北海道",
    hiroshima: "広島県",
    ishikawa: "石川県",
    okinawa: "沖縄県",
    kagoshima: "鹿児島県",
    miyazaki: "宮崎県",
    oita: "大分県",
    kumamoto: "熊本県",
    nagasaki: "長崎県",
    saga: "佐賀県",
    fukuoka: "福岡県",
    kochi: "高知県",
    ehime: "愛媛県",
    kagawa: "香川県",
    tokushima: "徳島県",
    yamaguchi: "山口県",
    okayama: "岡山県",
    shimane: "島根県",
    tottori: "鳥取県",
    wakayama: "和歌山県",
    nara: "奈良県",
    hyogo: "兵庫県",
    osaka: "大阪府",
    kyoto: "京都府",
    shiga: "滋賀県",
    mie: "三重県",
    aichi: "愛知県",
    shizuoka: "静岡県",
    gifu: "岐阜県",
    fukui: "福井県",
    toyama: "富山県",
    yamanashi: "山梨県",
    nagano: "長野県",
    nigata: "新潟県",
    kanagawa: "神奈川県",
    tokyo: "東京都",
    chiba: "千葉県",
    saitama: "埼玉県",
    gunma: "群馬県",
    tochigi: "栃木県",
    ibaraki: "茨城県",
    fukushima: "福島県",
    yamagata: "山形県",
    miyagi: "宮城県",
    akita: "秋田県",
    iwate: "岩手県",
    aomori: "青森県"
  }

  RAKUTEN_MAPPER = {
    ibaraki: 'ibaragi',
    yamanashi: 'yamanasi',
    chiba: 'tiba',
    shimane: 'simane',
    oita: 'ooita',
    nigata: 'niigata',
    kochi: 'kouchi',
    gifu: 'gihu',
    fukushima: 'hukushima',
    fukuoka: 'hukuoka',
    fukui: 'hukui'
  }
  # select area,count(*) from `courses` group by area;
  # これで抽出して、５件以上あるものを
  # https://hogehoge.tk/nihongo/
  # これでローマ字にする
  POPULAR_CITIES = {
    oosaka: "大阪",
    nagoya: "名古屋",
    kanazawa: "金沢",
    kyouto: "京都",
    hakone: "箱根",
    kamakura: "鎌倉",
    kawagutiko: "河口湖",
    hakodate: "函館",
    naha: "那覇",
    koube: "神戸",
    iwaki: "いわき",
    yokohama: "横浜",
    atami: "熱海",
    nasu: "那須",
    hida: "飛騨",
    karuizawa: "軽井沢",
    nikkou: "日光",
    hamamatu: "浜松",
    awazisima: "淡路島",
    nagasaki: "長崎",
    aso: "阿蘇",
    seinou: "西濃",
    kouhu: "甲府",
    isigakizima: "石垣島",
    asakusa: "浅草",
    kawagoe: "川越",
    sendai: "仙台",
    onomiti: "尾道",
    tottori: "鳥取",
    suwa: "諏訪",
    miyakozima: "宮古島",
    syoudosima: "小豆島",
    niigata: "新潟",
    yosino: "吉野",
    utunomiya: "宇都宮",
    aiz_wakamatu: "会津若松",
    tokorozawa: "所沢",
    minakami: "みなかみ",
    matue: "松江",
    hukuoka: "福岡",
    gihu: "岐阜",
    tyuunou: "中濃",
    tounou: "東濃",
  }

  CONDITIONS = {
    'day': '日帰り',
    '1day2': '1泊2日',
    '2day3': '2泊3日',
    '3day4': '3泊4日',
    train: '電車',
    car: 'ドライブ',
    nocar: '車なし',
    girl: '女子旅',
    one: 'ひとり旅',
    gourmet: 'グルメ'
  }

  SEASON = {
    spring: '春',
    summer: '夏',
    fall: '秋',
    winter: '冬'
  }
end
